---
namespace: community
name: docker-role-riane
version: 1.0.0
readme: README.md
authors:
  - Driss Riane
description: Installation de docker
license_file: BSD
tags:
  - v1
repository: https://github.com/DrissRiane/ansible-role-Docker-drissRiane.git
documentation: https://github.com/DrissRiane/ansible-role-Docker-drissRiane.git
homepage: https://github.com/DrissRiane/ansible-role-Docker-drissRiane.git
issues: https://github.com/DrissRiane/ansible-role-Docker-drissRiane.git
build_ignore:
  - .gitignore
 